#!/bin/sh

TICK=0.1

EXIT_USAGE=64

usage () {
    echo "Usage: ${0} seconds command" >&2
}

if [ "${#}" -lt 2 ]; then
    usage
    exit "${EXIT_USAGE}"
fi

interval="${1}"
shift
echo "${interval}" | grep '^[0-9]\+$'
if ( ! echo "${interval}" | grep -q '^[0-9]\+$' ); then
    usage
    exit "${EXIT_USAGE}"
fi

redraw () {
    clear
    eval "${@}"
}

trap 'redraw "${@}"' WINCH

last_redraw_time="$(date '+%s')"
redraw "${@}"
while true; do
    time="$(date '+%s')"
    elapsed="$(( ${time} - ${last_redraw_time} ))"
    if [ "${elapsed}" -ge "${interval}" ]; then
        redraw "${@}"
        last_redraw_time="${time}"
    fi
    sleep "${TICK}"
done
