.Dd August 30, 2020
.Dt WINCH 1
.Os
.Sh NAME
.Nm winch
.Nd Run a command, re-run on terminal resize, showing output fullscreen
.Sh USAGE
.Nm winch \(lB command ... \(rB
.Sh FUNCTION
.Nm
clears the terminal screen and runs the command at startup, and on each terminal resize event (SIGWINCH).
.Sh AUTHOR
.Nm Written by Vladimir Vrzić
.Sh LICENSE
.Nm
is distributed under the BSD 3-Clause License
